"""Part workflows grouped by catalog, project, UI state, and asset namespaces."""

from __future__ import annotations

import asyncio
import logging
import re
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from atopile.server.ui.store import Store
    from faebryk.libs.kicad.fileformats import kicad

from atopile import errors
from atopile.config import config
from atopile.data_models import (
    UiPartData,
    UiPartsSearchData,
    UiSidebarDetails,
)
from atopile.model.parts_search_jlc import search_jlc_parts
from atopile.pathutils import same_path
from faebryk.libs.ato_part import AtoPart
from faebryk.libs.part_lifecycle import PartIsNotAutoGenerated, PartLifecycle
from faebryk.libs.picker.api.api import get_api_client
from faebryk.libs.picker.api.models import Component, LCSCParams
from faebryk.libs.picker.lcsc import download_easyeda_info
from faebryk.libs.util import robustly_rm_dir

PARTS_SEARCH_DEBOUNCE_S = 0.25

__all__ = [
    "PARTS_SEARCH_DEBOUNCE_S",
    "PartAssets",
    "PartCatalog",
    "PartUiState",
    "ProjectParts",
]

_LOG = logging.getLogger(__name__)
_LCSC_RE = re.compile(r"^C?\d+$", re.IGNORECASE)
_DEFAULT_PCB_LAYER_TABLE: tuple[tuple[int, str, str], ...] = (
    (0, "F.Cu", "signal"),
    (31, "B.Cu", "signal"),
    (32, "B.Adhes", "user"),
    (33, "F.Adhes", "user"),
    (34, "B.Paste", "user"),
    (35, "F.Paste", "user"),
    (36, "B.SilkS", "user"),
    (37, "F.SilkS", "user"),
    (38, "B.Mask", "user"),
    (39, "F.Mask", "user"),
    (40, "Dwgs.User", "user"),
    (41, "Cmts.User", "user"),
    (42, "Eco1.User", "user"),
    (43, "Eco2.User", "user"),
    (44, "Edge.Cuts", "user"),
    (45, "Margin", "user"),
    (46, "B.CrtYd", "user"),
    (47, "F.CrtYd", "user"),
    (48, "B.Fab", "user"),
    (49, "F.Fab", "user"),
    (50, "User.1", "user"),
    (51, "User.2", "user"),
    (52, "User.3", "user"),
    (53, "User.4", "user"),
    (54, "User.5", "user"),
    (55, "User.6", "user"),
    (56, "User.7", "user"),
    (57, "User.8", "user"),
    (58, "User.9", "user"),
)


def _build_empty_pcb_template() -> str:
    layer_rows = "\n".join(
        f'    ({index} "{name}" {layer_type})'
        for index, name, layer_type in _DEFAULT_PCB_LAYER_TABLE
    )
    return (
        "(kicad_pcb\n"
        "  (version 20221018)\n"
        '  (generator "atopile-web-ide")\n'
        '  (generator_version "0.0.0")\n'
        "  (general)\n"
        '  (paper "A4")\n'
        "  (layers\n"
        f"{layer_rows}\n"
        "  )\n"
        "  (setup)\n"
        '  (net 0 "")\n'
        ")\n"
    )


_EMPTY_PCB_TEMPLATE = _build_empty_pcb_template()


class PartCatalog:
    """Part lookup, normalization, and UI payload assembly."""

    @classmethod
    def _normalize_lcsc_id(cls, raw: str) -> tuple[str, int] | None:
        candidate = str(raw).strip().upper() if raw else ""
        if not candidate:
            return None
        if not _LCSC_RE.match(candidate):
            return None
        numeric = int(candidate[1:] if candidate.startswith("C") else candidate)
        return f"C{numeric}", numeric

    @staticmethod
    def serialize_component(component: Component) -> dict:
        """Serialize a Component to a dict for API responses."""
        unit_cost = None
        if component.price:
            for price in component.price:
                if price.qFrom in (None, 0, 1):
                    unit_cost = float(price.price) if price.price is not None else None
                    break
            if unit_cost is None and component.price:
                unit_cost = (
                    float(component.price[0].price)
                    if component.price[0].price is not None
                    else None
                )

        return {
            "lcsc": component.lcsc_display,
            "manufacturer": component.manufacturer_name,
            "mpn": component.part_number,
            "package": component.package,
            "description": component.description,
            "datasheet_url": component.datasheet_url,
            "stock": component.stock,
            "unit_cost": unit_cost,
            "is_basic": bool(component.is_basic),
            "is_preferred": bool(component.is_preferred),
            "price": [
                {"qFrom": price.qFrom, "qTo": price.qTo, "price": price.price}
                for price in component.price
            ],
        }

    @classmethod
    def get_lcsc_parts(cls, lcsc_ids: Iterable[str]) -> dict:
        normalized: list[tuple[str, int]] = []
        seen: set[str] = set()
        for lcsc_id in lcsc_ids:
            parsed = cls._normalize_lcsc_id(lcsc_id)
            if parsed is None:
                raise ValueError(f"Invalid LCSC part number: {lcsc_id}")
            display, numeric = parsed
            if display in seen:
                continue
            seen.add(display)
            normalized.append((display, numeric))

        if not normalized:
            return {"parts": {}}

        client = get_api_client()
        params = [
            LCSCParams(lcsc=numeric, quantity=1) for _display, numeric in normalized
        ]
        results = client.fetch_parts_multiple(params)

        parts: dict[str, dict | None] = {}
        for (display, _numeric), components in zip(normalized, results, strict=False):
            parts[display] = (
                cls.serialize_component(components[0]) if components else None
            )

        return {"parts": parts}

    @staticmethod
    def search(query: str, *, limit: int = 50) -> tuple[list[dict], str | None]:
        return search_jlc_parts(query, limit=limit)

    @staticmethod
    def _installed_part_row(part: Mapping[str, object]) -> UiPartData:
        return UiPartData.model_validate(
            {
                **part,
                "identifier": part.get("identifier")
                or part.get("mpn")
                or part.get("lcsc")
                or "",
                "installed": True,
            }
        )

    @staticmethod
    def _search_part_row(
        part: Mapping[str, object],
        installed_match: Mapping[str, object] | None,
    ) -> UiPartData:
        return UiPartData.model_validate(
            {
                **part,
                "identifier": (
                    (installed_match.get("identifier") if installed_match else None)
                    or part.get("lcsc")
                    or part.get("mpn")
                    or ""
                ),
                "path": (
                    installed_match["path"]
                    if installed_match and installed_match.get("path")
                    else None
                ),
                "installed": bool(installed_match),
            }
        )

    @staticmethod
    def _matches_needle(row: UiPartData, needle: str) -> bool:
        if not needle:
            return True
        return any(
            value and needle in value.lower()
            for value in (
                row.identifier,
                row.mpn,
                row.lcsc,
                row.manufacturer,
                row.description,
            )
        )

    @classmethod
    def build_search_data(
        cls,
        *,
        project_root: str | None,
        query: str,
        installed_only: bool,
        limit: int = 50,
    ) -> UiPartsSearchData:
        if not project_root:
            return UiPartsSearchData(
                project_root=None,
                query=query,
                installed_only=installed_only,
                parts=[],
                loading=False,
            )

        installed_parts = ProjectParts.list_installed(project_root)
        installed_rows = [cls._installed_part_row(part) for part in installed_parts]
        needle = query.strip().lower()
        installed_matches = [
            row for row in installed_rows if cls._matches_needle(row, needle)
        ]

        if not needle or installed_only:
            return UiPartsSearchData(
                project_root=project_root,
                query=query,
                installed_only=installed_only,
                parts=installed_matches,
                loading=False,
            )

        search_results, error = cls.search(query, limit=limit)
        installed_lcsc_set = {
            (row.lcsc or "").strip().upper() for row in installed_matches if row.lcsc
        }
        installed_by_lcsc = {
            normalized_lcsc: part
            for part in installed_parts
            if (normalized_lcsc := str(part.get("lcsc") or "").strip().upper())
        }

        rows: list[UiPartData] = list(installed_matches)
        seen: set[str] = {
            (row.lcsc or "").strip().upper() or f"identifier:{row.identifier or ''}"
            for row in installed_matches
        }
        for part in search_results:
            lcsc = str(part.get("lcsc") or "")
            lcsc_key = lcsc.strip().upper()
            key = lcsc_key or f"identifier:{part.get('mpn') or ''}"
            if key in seen or lcsc_key in installed_lcsc_set:
                continue
            rows.append(
                cls._search_part_row(
                    part,
                    installed_by_lcsc.get(lcsc_key or ""),
                )
            )
            seen.add(key)

        return UiPartsSearchData(
            project_root=project_root,
            query=query,
            installed_only=installed_only,
            parts=rows,
            loading=False,
            error=error,
        )

    @classmethod
    def get_details(
        cls,
        lcsc_id: str,
        *,
        project_root: str | None = None,
        identifier: str | None = None,
        installed: bool = False,
    ) -> UiPartData | None:
        if cls._normalize_lcsc_id(lcsc_id) is None:
            raise ValueError(f"Invalid LCSC part number: {lcsc_id}")

        results, _error = search_jlc_parts(lcsc_id, limit=1)
        if not results:
            return None
        part = results[0]

        installed_identifier, path, import_statement = cls._installed_part_project_info(
            project_root=project_root,
            lcsc_id=lcsc_id,
            installed=installed,
        )

        return UiPartData.model_validate(
            {
                **part,
                "identifier": (
                    installed_identifier
                    or identifier
                    or part.get("mpn")
                    or part.get("lcsc")
                    or ""
                ),
                "path": path,
                "import_statement": import_statement,
                "installed": installed,
            }
        )

    @staticmethod
    def _installed_part_project_info(
        *,
        project_root: str | None,
        lcsc_id: str,
        installed: bool,
    ) -> tuple[str | None, str | None, str | None]:
        """Return (identifier, path, import_statement) for an installed part."""
        if not (installed and project_root):
            return None, None, None

        config.apply_options(None, working_dir=Path(project_root))
        parts_path = config.project.paths.parts
        if not parts_path.exists():
            return None, None, None

        target_lcsc = lcsc_id.strip().upper()

        for part_dir in sorted(parts_path.iterdir()):
            if not part_dir.is_dir():
                continue
            ato_file = part_dir / f"{part_dir.name}.ato"
            if not ato_file.exists():
                continue
            try:
                part = AtoPart.load(part_dir)
            except Exception:
                continue

            supplier_partno = None
            if part.pick_part and part.pick_part.supplier.supplier_id.lower() == "lcsc":
                supplier_partno = part.pick_part.supplier_partno
            if not supplier_partno or supplier_partno.strip().upper() != target_lcsc:
                continue

            return (
                part.identifier,
                str(part_dir),
                part.generate_import_statement(config.project.paths.src),
            )

        return None, None, None


class PartUiState:
    """Parts panel/detail state transitions and store refresh flow."""

    @staticmethod
    def empty_search_state(
        current: UiPartsSearchData | None = None,
        *,
        project_root: str | None,
    ) -> UiPartsSearchData:
        state = current or UiPartsSearchData()
        return state.model_copy(
            update={
                "project_root": project_root,
                "parts": [],
                "loading": False,
                "error": None,
                "action_error": None,
            }
        )

    @staticmethod
    def search_loading_state(
        current: UiPartsSearchData,
        *,
        project_root: str | None,
        query: str,
        installed_only: bool,
    ) -> UiPartsSearchData:
        return current.model_copy(
            update={
                "project_root": project_root,
                "query": query,
                "installed_only": installed_only,
                "parts": current.parts
                if same_path(current.project_root, project_root)
                else [],
                "loading": bool(project_root and query.strip() and not installed_only),
                "error": None,
                "action_error": None,
            }
        )

    @staticmethod
    def search_error_state(
        current: UiPartsSearchData,
        *,
        project_root: str | None,
        query: str,
        installed_only: bool,
        error: str,
    ) -> UiPartsSearchData:
        return current.model_copy(
            update={
                "project_root": project_root,
                "query": query,
                "installed_only": installed_only,
                "parts": [],
                "loading": False,
                "error": error,
            }
        )

    @classmethod
    def is_selected(
        cls,
        details_state: UiSidebarDetails,
        *,
        project_root: str,
        lcsc: str,
    ) -> bool:
        return (
            details_state.view == "part"
            and same_path(details_state.part.project_root, project_root)
            and (
                str(details_state.part.lcsc).strip().upper()
                if details_state.part.lcsc
                else ""
            )
            == (str(lcsc).strip().upper() if lcsc else "")
        )

    @classmethod
    def set_action_state(
        cls,
        store: Store,
        *,
        project_root: str,
        lcsc: str,
        action: str,
        action_error: str | None = None,
    ) -> None:
        normalized_lcsc = str(lcsc).strip().upper() if lcsc else ""
        parts_state = cast(UiPartsSearchData, store.get("parts_search"))
        if same_path(parts_state.project_root, project_root):
            store.set(
                "parts_search",
                parts_state.model_copy(
                    update={
                        "parts": [
                            row.model_copy(
                                update={
                                    "action": (
                                        action
                                        if normalized_lcsc
                                        and (
                                            str(row.lcsc).strip().upper()
                                            if row.lcsc
                                            else ""
                                        )
                                        == normalized_lcsc
                                        else "idle"
                                    )
                                }
                            )
                            for row in parts_state.parts
                        ],
                        "action_error": action_error,
                    }
                ),
            )

        details_state = cast(UiSidebarDetails, store.get("sidebar_details"))
        if cls.is_selected(details_state, project_root=project_root, lcsc=lcsc):
            current_part = details_state.part.details
            store.set(
                "sidebar_details",
                details_state.model_copy(
                    update={
                        "part": details_state.part.model_copy(
                            update={
                                "details": (
                                    current_part.model_copy(update={"action": action})
                                    if current_part
                                    else None
                                ),
                                "action_error": action_error,
                            }
                        )
                    }
                ),
            )

    @classmethod
    async def refresh_search(
        cls,
        store: Store,
        *,
        project_root: str | None,
        query: str,
        installed_only: bool,
        limit: int = 50,
    ) -> UiPartsSearchData:
        state = await asyncio.to_thread(
            PartCatalog.build_search_data,
            project_root=project_root,
            query=query,
            installed_only=installed_only,
            limit=limit,
        )
        store.set("parts_search", state)
        return state

    @classmethod
    async def refresh_search_from_store(
        cls,
        store: Store,
        *,
        limit: int = 50,
    ) -> UiPartsSearchData:
        current = cast(UiPartsSearchData, store.get("parts_search"))
        return await cls.refresh_search(
            store,
            project_root=current.project_root,
            query=current.query,
            installed_only=current.installed_only,
            limit=limit,
        )

    @classmethod
    async def show_details(
        cls,
        store: Store,
        *,
        project_root: str | None,
        lcsc: str | None,
        identifier: str | None = None,
        installed: bool = False,
        seed: UiPartData | None = None,
        action_error: str | None = None,
    ) -> None:
        part = seed or cls._make_part_seed(
            search_state=cast(UiPartsSearchData, store.get("parts_search")),
            project_root=project_root,
            identifier=identifier,
            lcsc=lcsc,
            installed=installed,
        )
        state = cls._set_details(
            cast(UiSidebarDetails, store.get("sidebar_details")),
            project_root=project_root,
            lcsc=lcsc,
            details=part,
            loading=bool(lcsc),
            action_error=action_error,
        )
        store.set("sidebar_details", state)
        store.set(
            "sidebar_details",
            await cls.load_details(
                state,
                project_root=project_root,
                lcsc=lcsc,
                identifier=identifier,
                installed=installed,
                seed=seed,
                action_error=action_error,
            ),
        )

    @classmethod
    async def refresh_open_details(
        cls,
        store: Store,
        *,
        project_root: str,
        lcsc: str,
        installed: bool,
    ) -> None:
        details_state = cast(UiSidebarDetails, store.get("sidebar_details"))
        if not cls.is_selected(details_state, project_root=project_root, lcsc=lcsc):
            return

        selected_part = details_state.part.details
        await cls.show_details(
            store,
            project_root=project_root,
            identifier=selected_part.identifier if selected_part else None,
            lcsc=lcsc,
            installed=installed,
        )

    @classmethod
    async def load_details(
        cls,
        state: UiSidebarDetails,
        *,
        project_root: str | None,
        lcsc: str | None,
        identifier: str | None = None,
        installed: bool = False,
        seed: UiPartData | None = None,
        action_error: str | None = None,
    ) -> UiSidebarDetails:
        base_part = seed or state.part.details
        if not lcsc:
            return cls._set_details(
                state,
                project_root=project_root,
                lcsc=lcsc,
                details=base_part,
                loading=False,
                error="This part does not have an LCSC identifier.",
                action_error=action_error,
            )

        try:
            detail = await asyncio.to_thread(
                PartCatalog.get_details,
                lcsc,
                project_root=project_root,
                identifier=identifier or (base_part.identifier if base_part else None),
                installed=installed,
            )
        except Exception as exc:
            return cls._set_details(
                state,
                project_root=project_root,
                lcsc=lcsc,
                details=base_part,
                loading=False,
                error=str(exc),
                action_error=action_error,
            )

        if detail is None:
            return cls._set_details(
                state,
                project_root=project_root,
                lcsc=lcsc,
                details=base_part,
                loading=False,
                error=f"No details found for {lcsc}.",
                action_error=action_error,
            )

        return cls._set_details(
            state,
            project_root=project_root,
            lcsc=lcsc,
            details=detail,
            loading=False,
            action_error=action_error,
        )

    @staticmethod
    def _set_details(
        state: UiSidebarDetails,
        *,
        project_root: str | None,
        lcsc: str | None,
        details: UiPartData | None,
        loading: bool,
        error: str | None = None,
        action_error: str | None = None,
    ) -> UiSidebarDetails:
        current_lcsc = (state.part.lcsc or "").strip().upper()
        next_lcsc = (lcsc or "").strip().upper()
        preserve_action = same_path(state.part.project_root, project_root) and (
            current_lcsc == next_lcsc
        )
        next_action = (
            state.part.details.action
            if preserve_action and state.part.details
            else "idle"
        )
        next_details = (
            details.model_copy(update={"action": next_action}) if details else None
        )
        return state.model_copy(
            update={
                "view": "part",
                "part": state.part.model_copy(
                    update={
                        "project_root": project_root,
                        "lcsc": lcsc,
                        "details": next_details,
                        "loading": loading,
                        "error": error,
                        "action_error": action_error,
                    }
                ),
            }
        )

    @staticmethod
    def _make_part_seed(
        *,
        search_state: UiPartsSearchData,
        project_root: str | None,
        identifier: str | None,
        lcsc: str | None,
        installed: bool,
    ) -> UiPartData:
        search_match = next(
            (
                part
                for part in search_state.parts
                if (identifier and part.identifier == identifier)
                or (lcsc and part.lcsc == lcsc)
            ),
            None,
        )
        if search_match:
            return search_match.model_copy(
                update={
                    "identifier": (
                        search_match.identifier
                        or identifier
                        or lcsc
                        or search_match.mpn
                        or ""
                    ),
                    "lcsc": search_match.lcsc or lcsc,
                    "installed": search_match.installed or installed,
                }
            )

        return UiPartData(
            identifier=identifier or lcsc or "",
            lcsc=lcsc,
            mpn=identifier or lcsc or "",
            installed=installed,
            path=str(Path(project_root) / "parts" / identifier)
            if project_root and installed and identifier
            else None,
        )


class ProjectParts:
    """Project-local part install, uninstall, and discovery workflows."""

    @staticmethod
    def install_raw(lcsc_id: str, project_root: str) -> dict:
        config.apply_options(None, working_dir=Path(project_root))

        try:
            epart = download_easyeda_info(lcsc_id, get_model=True)
            apart = PartLifecycle.singleton().library.ingest_part_from_easyeda(epart)
        except PartIsNotAutoGenerated as exc:
            raise errors.UserException(
                f"Part `{exc.part.path}` already exists and is manually modified."
            ) from exc
        except Exception as exc:
            raise errors.UserException(str(exc)) from exc

        return {
            "identifier": apart.identifier,
            "path": str(apart.path),
        }

    @classmethod
    async def install(
        cls,
        store: Store,
        *,
        project_root: str,
        lcsc: str,
    ) -> dict[str, Any]:
        PartUiState.set_action_state(
            store,
            project_root=project_root,
            lcsc=lcsc,
            action="installing",
        )
        try:
            result = await asyncio.to_thread(cls.install_raw, lcsc, project_root)
            await PartUiState.refresh_search_from_store(store)
            await PartUiState.refresh_open_details(
                store,
                project_root=project_root,
                lcsc=lcsc,
                installed=True,
            )
            PartUiState.set_action_state(
                store,
                project_root=project_root,
                lcsc=lcsc,
                action="idle",
            )
            return result
        except Exception as exc:
            PartUiState.set_action_state(
                store,
                project_root=project_root,
                lcsc=lcsc,
                action="idle",
                action_error=str(exc),
            )
            raise

    @staticmethod
    def _next_available_package_name(project_root: Path, base: str) -> str:
        packages_dir = project_root / "packages"
        if not (packages_dir / base).exists():
            return base
        for suffix in range(2, 1000):
            candidate = f"{base}_{suffix}"
            if not (packages_dir / candidate).exists():
                return candidate
        raise errors.UserException(
            f"Could not find a free package slot for `{base}` after 1000 attempts."
        )

    @classmethod
    def convert_to_package_raw(
        cls,
        lcsc_id: str,
        project_root: str,
    ) -> dict[str, str | bool | dict[str, str]]:
        """Promote an already-installed part to its own local package."""
        from atopile.model import projects as projects_domain

        installed = cls.list_installed(project_root)
        target = lcsc_id.strip().upper()
        match = next(
            (
                part
                for part in installed
                if str(part.get("lcsc", "")).strip().upper() == target
            ),
            None,
        )
        if match is None:
            raise errors.UserException(
                f"Part {lcsc_id} is not installed at the project root."
            )

        base_name = str(match.get("identifier", "")).replace("_package", "")
        if not base_name:
            raise errors.UserException(f"Installed part {lcsc_id} has no identifier")

        package_name = cls._next_available_package_name(Path(project_root), base_name)
        package_info = projects_domain.create_local_package(
            Path(project_root),
            package_name,
            package_name,
            f"Local wrapper package for {package_name}",
        )
        package_root = Path(package_info["path"])
        packaged = cls.install_raw(lcsc_id, str(package_root))

        raw_identifier = str(packaged.get("identifier", "")).replace("_package", "")
        raw_component_name = f"{raw_identifier}_package"
        wrapper_path = Path(package_info["module_path"])
        wrapper_path.write_text(
            (
                f'from "parts/{raw_identifier}/{raw_identifier}.ato" import '
                f"{raw_component_name}\n\n"
                f"module {package_name}:\n"
                f"    package = new {raw_component_name}\n"
            ),
            encoding="utf-8",
        )

        cls.uninstall_raw(lcsc_id, project_root)

        return {
            "created_package": True,
            "package": package_info,
            "identifier": package_info["identifier"],
            "path": package_info["module_path"],
            "entry_module": package_name,
            "part_identifier": str(packaged.get("identifier", "")),
            "part_path": str(packaged.get("path", "")),
            "import_statement": package_info["import_statement"],
        }

    @classmethod
    def install_as_package(
        cls,
        lcsc_id: str,
        project_root: str,
    ) -> dict[str, str | bool | dict[str, str]]:
        """Install an LCSC part and immediately promote it to a local package."""
        cls.install_raw(lcsc_id, project_root)
        return cls.convert_to_package_raw(lcsc_id, project_root)

    @classmethod
    async def convert_to_package(
        cls,
        store: Store,
        *,
        project_root: str,
        lcsc: str,
    ) -> dict[str, Any]:
        PartUiState.set_action_state(
            store,
            project_root=project_root,
            lcsc=lcsc,
            action="converting",
        )
        try:
            result = await asyncio.to_thread(
                cls.convert_to_package_raw, lcsc, project_root
            )
            await PartUiState.refresh_search_from_store(store)
            await PartUiState.refresh_open_details(
                store,
                project_root=project_root,
                lcsc=lcsc,
                installed=False,
            )
            PartUiState.set_action_state(
                store,
                project_root=project_root,
                lcsc=lcsc,
                action="idle",
            )
            return result
        except Exception as exc:
            PartUiState.set_action_state(
                store,
                project_root=project_root,
                lcsc=lcsc,
                action="idle",
                action_error=str(exc),
            )
            raise

    @staticmethod
    def list_installed(project_root: str) -> list[dict]:
        config.apply_options(None, working_dir=Path(project_root))
        parts_path = config.project.paths.parts
        if not parts_path.exists():
            return []

        installed_parts: list[dict] = []
        for part_dir in sorted(parts_path.iterdir()):
            if not part_dir.is_dir():
                continue
            ato_file = part_dir / f"{part_dir.name}.ato"
            if not ato_file.exists():
                continue
            try:
                part = AtoPart.load(part_dir)
            except Exception:
                continue

            lcsc_id = None
            if part.pick_part and part.pick_part.supplier.supplier_id.lower() == "lcsc":
                lcsc_id = part.pick_part.supplier_partno

            installed_parts.append(
                {
                    "identifier": part.identifier,
                    "manufacturer": part.mfn[0],
                    "mpn": part.mfn[1],
                    "lcsc": lcsc_id,
                    "datasheet_url": part.datasheet,
                    "description": part.docstring,
                    "path": str(part.path),
                }
            )

        return installed_parts

    @staticmethod
    def uninstall_raw(lcsc_id: str, project_root: str) -> dict:
        config.apply_options(None, working_dir=Path(project_root))
        parts_path = config.project.paths.parts
        if not parts_path.exists():
            raise errors.UserException("No parts installed in this project.")

        target = lcsc_id.strip().upper()
        for part_dir in sorted(parts_path.iterdir()):
            if not part_dir.is_dir():
                continue
            ato_file = part_dir / f"{part_dir.name}.ato"
            if not ato_file.exists():
                continue
            try:
                part = AtoPart.load(part_dir)
            except Exception:
                continue

            supplier_partno = None
            if part.pick_part and part.pick_part.supplier.supplier_id.lower() == "lcsc":
                supplier_partno = part.pick_part.supplier_partno

            if not supplier_partno or supplier_partno.strip().upper() != target:
                continue

            if not part.auto_generated:
                raise errors.UserException(
                    f"Part `{part.path}` is manually modified; "
                    "remove is_auto_generated to delete."
                )

            robustly_rm_dir(part.path)
            return {
                "identifier": part.identifier,
                "path": str(part.path),
            }

        raise errors.UserException(f"Part {lcsc_id} not found in this project.")

    @classmethod
    async def uninstall(
        cls,
        store: Store,
        *,
        project_root: str,
        lcsc: str,
    ) -> dict[str, Any]:
        PartUiState.set_action_state(
            store,
            project_root=project_root,
            lcsc=lcsc,
            action="uninstalling",
        )
        try:
            result = await asyncio.to_thread(cls.uninstall_raw, lcsc, project_root)
            await PartUiState.refresh_search_from_store(store)
            await PartUiState.refresh_open_details(
                store,
                project_root=project_root,
                lcsc=lcsc,
                installed=False,
            )
            PartUiState.set_action_state(
                store,
                project_root=project_root,
                lcsc=lcsc,
                action="idle",
            )
            return result
        except Exception as exc:
            PartUiState.set_action_state(
                store,
                project_root=project_root,
                lcsc=lcsc,
                action="idle",
                action_error=str(exc),
            )
            raise


class PartAssets:
    """Footprint and 3D model fetchers for parts."""

    @staticmethod
    def _lib_fp_to_pcb_fp(lib_fp: kicad.footprint.Footprint) -> kicad.pcb.Footprint:
        from faebryk.libs.kicad.fileformats import kicad

        common_fields = {
            field: getattr(lib_fp, field)
            for field in set(kicad.footprint.Footprint.__field_names__())
            & set(kicad.pcb.Footprint.__field_names__())
        }
        common_fields["pads"] = [
            kicad.pcb.Pad(
                **{
                    field: getattr(pad, field)
                    for field in kicad.pcb.Pad.__field_names__()
                },
            )
            for pad in lib_fp.pads
        ]
        common_fields["uuid"] = kicad.gen_uuid()

        pcb_fp = kicad.pcb.Footprint(
            at=kicad.pcb.Xyr(x=0, y=0, r=0),
            **common_fields,
        )
        pcb_fp.propertys.clear()
        pcb_fp.fp_texts.clear()
        return pcb_fp

    @classmethod
    def get_footprint(cls, lcsc_id: str) -> bytes | None:
        from easyeda2kicad.easyeda.easyeda_api import EasyedaApi
        from easyeda2kicad.easyeda.easyeda_importer import EasyedaFootprintImporter
        from easyeda2kicad.kicad.export_kicad_footprint import ExporterFootprintKicad

        from faebryk.libs.kicad.fileformats import kicad
        from faebryk.libs.util import call_with_file_capture

        normalized = PartCatalog._normalize_lcsc_id(lcsc_id)
        if normalized is None:
            raise ValueError(f"Invalid LCSC part number: {lcsc_id}")
        lcsc_str, _lcsc_numeric = normalized

        try:
            from faebryk.libs.picker.lcsc import _easyeda_api_retry

            api = EasyedaApi()
            cad_data = _easyeda_api_retry(
                lambda: api.get_cad_data_of_component(lcsc_id=lcsc_str)
            )
            if not cad_data:
                return None

            easyeda_footprint = EasyedaFootprintImporter(
                easyeda_cp_cad_data=cad_data
            ).get_footprint()
            exporter = ExporterFootprintKicad(easyeda_footprint)
            fp_raw = call_with_file_capture(
                lambda path: exporter.export(str(path), None)
            )[1]
            fp_file = kicad.loads(
                kicad.footprint_v5.FootprintFile,
                fp_raw.decode("utf-8"),
            )
            fp_file = kicad.convert(fp_file)

            template_pcb = kicad.loads(kicad.pcb.PcbFile, _EMPTY_PCB_TEMPLATE)
            pcb = template_pcb.kicad_pcb
            pcb.footprints.clear()
            pcb.footprints.append(cls._lib_fp_to_pcb_fp(fp_file.footprint))
            pcb.nets.clear()
            pcb.zones.clear()
            pcb.segments.clear()
            pcb.vias.clear()
            pcb.gr_texts.clear()
            pcb.gr_text_boxes.clear()
            return kicad.dumps(template_pcb).encode("utf-8")
        except Exception as exc:
            _LOG.warning("Failed to get footprint for %s: %s", lcsc_id, exc)
            return None

    @classmethod
    def get_model(cls, lcsc_id: str) -> tuple[bytes, str] | None:
        from easyeda2kicad.easyeda.easyeda_api import EasyedaApi
        from easyeda2kicad.easyeda.easyeda_importer import EasyedaFootprintImporter

        normalized = PartCatalog._normalize_lcsc_id(lcsc_id)
        if normalized is None:
            raise ValueError(f"Invalid LCSC part number: {lcsc_id}")
        lcsc_str, _lcsc_numeric = normalized

        try:
            from faebryk.libs.picker.lcsc import _easyeda_api_retry

            api = EasyedaApi()
            cad_data = _easyeda_api_retry(
                lambda: api.get_cad_data_of_component(lcsc_id=lcsc_str)
            )
            if not cad_data:
                return None

            easyeda_footprint = EasyedaFootprintImporter(
                easyeda_cp_cad_data=cad_data
            ).get_footprint()
            if easyeda_footprint.model_3d is None:
                return None

            model_data = api.get_step_3d_model(uuid=easyeda_footprint.model_3d.uuid)
            if model_data is None:
                return None

            return model_data, easyeda_footprint.model_3d.name
        except Exception as exc:
            _LOG.warning("Failed to get 3D model for %s: %s", lcsc_id, exc)
            return None
